"""
ChromaDB Configuration Module
==============================

Production-grade configuration and orchestration layer for ChromaDB,
serving as the single source of truth for vector database configuration,
collection lifecycle management, embedding model consistency, and
document routing metadata.

This module ensures that all ingestion and retrieval pipelines use the
same embedding model, storage directory, and collection configuration,
which is critical for semantic search correctness.

Primary Responsibilities
------------------------
1. Persistent Client Initialization
   Creates and manages ChromaDB persistent client instances that survive
   process restarts and ensure long-term storage durability.

2. Collection Lifecycle Management
   Handles creation, retrieval, and resetting of collections while
   enforcing consistent embedding configuration.

3. Embedding Model Configuration
   Provides a centralized embedding function using all-mpnet-base-v2,
   ensuring semantic consistency across ingestion and query pipelines.

4. Document Routing via DOCUMENT_REGISTRY
   Defines metadata that controls how documents are categorized,
   routed, filtered, and retrieved by downstream agents.

5. Multi-Agent Support
   Enables agent-specific retrieval for:

      - Dispatcher Agent (Complaint routing)
      - Sentinel Agent (Fraud detection and risk analysis)
      - Trajectory Agent (Product recommendation logic)
      - Customer Agent (Customer-facing FAQ retrieval)

Architecture Flow
-----------------

    Document Generator / Source Files
               ↓
    DOCUMENT_REGISTRY (routing metadata)
               ↓
    DocumentIngester (chunking + tagging)
               ↓
    ChromaDBConfig (embedding + collections)
               ↓
    ChromaDB Collections (vector storage)
               ↓
    RetrievalEngine (semantic search)
               ↓
    RAGQueryEngine (context assembly)
               ↓
    AI Agents (Dispatcher, Sentinel, Trajectory, Customer)

Design Guarantees
-----------------
- Embedding consistency across ingestion and retrieval
- Persistent, production-safe storage
- Structured document routing and metadata filtering
- Deterministic collection configuration
- Safe reset and re-ingestion workflows

Embedding Model Selection
-------------------------
Model: all-mpnet-base-v2

Chosen because:
- High semantic accuracy
- 768-dimensional vectors
- Strong performance on compliance, policy, and fraud datasets
- Industry standard for enterprise-grade RAG pipelines

Author: AI Engineer 2
Date: February 2026
"""


# =============================================================================
# Imports
# =============================================================================

import chromadb  # Core ChromaDB package for vector database operations

from chromadb.api import ClientAPI  
# ClientAPI defines the interface contract for ChromaDB clients,
# ensuring type safety and compatibility across implementations.

from chromadb.utils import embedding_functions  
# Provides embedding function wrappers compatible with ChromaDB,
# including SentenceTransformerEmbeddingFunction.

from pathlib import Path  
# Used for cross-platform filesystem path handling.
from chromadb.config import Settings
from typing import Optional, Dict, Tuple  
# Provides static typing support for better maintainability and clarity.

import logging  
# Standard Python logging system for structured operational logging.


# =============================================================================
# Logging Configuration
# =============================================================================

logging.basicConfig(
    level=logging.INFO,  
    # Sets logging level to INFO to capture operational events.

    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    # Defines structured log format including timestamp, module name,
    # log level, and message.
)

logger = logging.getLogger(__name__)  
# Creates a module-specific logger using the module name.
# This allows precise filtering and debugging.


# =============================================================================
# DOCUMENT REGISTRY
# =============================================================================
"""
DOCUMENT_REGISTRY is the authoritative routing table for all documents
stored in the vector database.

This registry maps each document ID to metadata that controls:

• Collection routing
• Agent targeting
• Retrieval filtering
• Version tracking
• Document categorization

This registry ensures deterministic routing and retrieval behavior.

Critical Requirements
---------------------

Keys MUST match:

1. document_id generated by BankingPolicyGenerator._package_for_rag()

2. Corresponding .txt filenames saved in:

       knowledge_base/

Example:

    knowledge_base/POL-CCH-001.txt

DocumentIngester reads this registry and attaches metadata to every chunk.

Metadata Attached to Each Chunk
-------------------------------

- title
- category
- version
- agent_target
- doc_type_flag
- description

Routing Logic
-------------

doc_type_flag determines collection routing:

    policy         → bank_policies collection
    knowledge_base → customer_faqs collection

Both also go into:

    all_documents collection

Agent Filtering
---------------

Enables targeted retrieval:

Example:

    collection.query(
        where={"agent_target": "Sentinel"}
    )

This allows Sentinel Agent to retrieve only fraud-related documents.
"""

DOCUMENT_REGISTRY: Dict[str, Dict] = {

    # Unique document ID used as primary routing key
    "POL-CCH-001": {

        "title": "Customer Complaint Handling Policy",
        # Human-readable document title

        "category": "policy",
        # Logical grouping category

        "version": "2.1",
        # Version number for auditability and upgrade tracking

        "agent_target": "Dispatcher",
        # Primary agent responsible for using this document

        "doc_type_flag": "policy",
        # Controls collection routing

        "description": "Complaint routing rules, escalation matrix, SLA timelines",
        # Additional context description
    },

    "FRM-001": {

        "title": "Fraud Detection and Prevention Guidelines",

        "category": "security",

        "version": "4.0",

        "agent_target": "Sentinel",

        "doc_type_flag": "policy",

        "description": "Fraud detection rules, risk scoring 0–100, fraud escalation",
    },

    "TSU-POL-002": {

        "title": "Transaction Processing Policies",

        "category": "operations",

        "version": "4.0",

        "agent_target": "All",
        # Indicates all agents may use this document

        "doc_type_flag": "policy",

        "description": "Transaction processing rules, reversals, and processing SLA",
    },

    "FAQ-001": {

        "title": "Customer Frequently Asked Questions",

        "category": "knowledge_base",

        "version": "2.0",

        "agent_target": "Customer",

        "doc_type_flag": "knowledge_base",
        # Ensures routing into FAQ collection

        "description": "Customer-facing FAQs and help content",
    },

    "FRM-002": {

        "title": "Merchant Risk Profiles",

        "category": "security",

        "version": "1.0",

        "agent_target": "Sentinel",

        "doc_type_flag": "policy",

        "description": "Merchant risk categories and fraud risk weights",
    },

    "PRS-001": {

        "title": "Product Recommendation Policy",

        "category": "policy",

        "version": "1.0",

        "agent_target": "Trajectory",

        "doc_type_flag": "policy",

        "description": "Product eligibility rules and recommendation logic",
    },
}


# =============================================================================
# ChromaDB Configuration Class
# =============================================================================

class ChromaDBConfig:
    """
    Central configuration controller for ChromaDB.

    This class ensures consistent configuration across all ingestion
    and retrieval workflows.

    Responsibilities
    ----------------

    1. Persistent client creation
    2. Embedding function management
    3. Collection lifecycle control
    4. Consistent metadata enforcement

    Why This Class Exists
    ---------------------

    Prevents configuration drift between ingestion and retrieval.

    Ensures:

    • Same embedding model everywhere
    • Same storage directory everywhere
    • Same metadata configuration everywhere

    Without this class, semantic search would break.

    Embedding Model
    ----------------

    all-mpnet-base-v2

    Advantages:

    • High semantic accuracy
    • Excellent fraud / policy comprehension
    • 768-dimension embeddings
    • Industry-grade performance
    """

    # Collection storing policy and operational documents
    COLLECTION_POLICIES = "bank_policies"

    # Collection storing customer-facing FAQs
    COLLECTION_FAQS = "customer_faqs"

    # Master collection storing all documents
    COLLECTION_ALL = "all_documents"


    # Selected embedding model
    EMBEDDING_MODEL = "all-mpnet-base-v2"

    # Distance metric used for similarity search
    DISTANCE_METRIC = "cosine"


    def __init__(self, persist_directory: Optional[Path] = None):
        """
        Initializes ChromaDB configuration object.

        This prepares the persistence directory and ensures storage
        location is valid.

        Args:
            persist_directory:
                Optional custom storage path.

                Default:
                    project_root/chroma_db/

        Behavior:
            - Creates directory if missing
            - Stores resolved path
            - Logs configuration
        """

        if persist_directory is None:
            persist_directory = Path(__file__).parent.parent / "chroma_db"
            # Default storage directory relative to project root

        self.persist_directory = Path(persist_directory)
        # Converts to Path object for consistent filesystem operations

        self.persist_directory.mkdir(parents=True, exist_ok=True)
        # Creates directory safely if missing

        logger.info(
            f"ChromaDB persistence directory: {self.persist_directory}"
        )
        # Logs resolved storage path
  

    def get_embedding_function(self):
        """
        Creates and returns embedding function instance.

        CRITICAL REQUIREMENT:
        Same embedding model MUST be used for ingestion and retrieval.

        If different models are used, semantic similarity breaks.

        Returns:
            SentenceTransformerEmbeddingFunction instance

        Used by:
            - Collection creation
            - Document ingestion
            - Query embedding
        """

        logger.info(f"Loading embedding model: {self.EMBEDDING_MODEL}")

        return embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name=self.EMBEDDING_MODEL
        )


    def create_client(self) -> ClientAPI:
        """
        Creates persistent ChromaDB client.

        Persistent client ensures vector database survives process restart.

        Returns:
            Configured PersistentClient instance
        """

        self.persist_directory.mkdir(parents=True, exist_ok=True)

        settings = Settings(
            persist_directory=str(self.persist_directory),
            anonymized_telemetry=False,
            allow_reset=True,
            is_persistent=True,
        )

        client = chromadb.PersistentClient(
            path=str(self.persist_directory),
            settings=settings
        )

        logger.info(
            f"ChromaDB PersistentClient initialized at {self.persist_directory}"
        )

        return client   

    def get_or_create_collection(
        self,
        client: ClientAPI,
        collection_name: str,
        metadata: Optional[Dict] = None
    ):
        """
        Retrieves existing collection or creates new one.

        Guarantees consistent embedding function usage.

        Args:
            client:
                ChromaDB client instance

            collection_name:
                Name of collection

            metadata:
                Optional metadata dictionary

        Returns:
            ChromaDB collection instance
        """

        embedding_function = self.get_embedding_function()
        # Ensures collection uses correct embedding model

        if metadata is None:

            metadata = {
                "description": f"Banking collection: {collection_name}",

                "embedding_model": self.EMBEDDING_MODEL,

                "distance_metric": self.DISTANCE_METRIC,

                "document_registry_size": str(len(DOCUMENT_REGISTRY)),
            }
            # Defines default metadata


        try:

            collection = client.get_collection(
                name=collection_name,
                embedding_function=embedding_function
            )
            # Attempts to retrieve existing collection

            logger.info(f"Retrieved existing collection: {collection_name}")

        except Exception:

            collection = client.create_collection(
                name=collection_name,
                embedding_function=embedding_function,
                metadata=metadata
            )
            # Creates collection if missing

            logger.info(f"Created new collection: {collection_name}")

        return collection


    def reset_collection(self, client: ClientAPI, collection_name: str):
        """
        Deletes and recreates collection.

        Used to prevent duplicate chunks during re-ingestion.

        Args:
            client:
                ChromaDB client

            collection_name:
                Collection to reset
        """

        try:

            client.delete_collection(name=collection_name)
            # Deletes existing collection

            logger.info(f"Deleted collection: {collection_name}")

        except Exception:

            logger.warning(f"Collection did not exist: {collection_name}")

        self.get_or_create_collection(client, collection_name)
        # Recreates collection

        logger.info(f"Reset complete: {collection_name}")


    def reset_all_collections(self, client: ClientAPI):
        """
        Resets all collections.

        Ensures clean database before full ingestion.

        Args:
            client:
                ChromaDB client instance
        """

        for name in [
            self.COLLECTION_POLICIES,
            self.COLLECTION_FAQS,
            self.COLLECTION_ALL
        ]:

            self.reset_collection(client, name)
            # Reset each collection

        logger.info("All collections reset and ready for fresh ingestion")


# =============================================================================
# Initialization Helper
# =============================================================================

def initialize_chromadb() -> Tuple[ClientAPI, "ChromaDBConfig"]:
    """
    Initializes and returns ChromaDB client and configuration.

    Returns:
        Tuple containing:

            client → ChromaDB client
            config → Configuration object

    Used by:
        - DocumentIngester
        - RetrievalEngine
        - RAGQueryEngine
        - Agent systems
    """

    config = ChromaDBConfig()
    # Creates config object

    client = config.create_client()
    # Creates persistent client

    return client, config


# =============================================================================
# Collection Statistics Helper
# =============================================================================

def get_collection_stats(collection) -> Dict:
    """
    Retrieves operational statistics from collection.

    Useful for:

    • Monitoring ingestion success
    • Debugging retrieval
    • System observability

    Returns:
        Dictionary containing collection metadata and stats
    """

    try:

        count = collection.count()
        # Gets number of stored documents

        if count > 0:

            sample = collection.peek(limit=1)
            # Retrieves sample document

            sample_metadata = (
                sample["metadatas"][0] if sample["metadatas"] else {}
            )

        else:

            sample_metadata = {}

        return {

            "collection_name": collection.name,

            "document_count": count,

            "metadata": collection.metadata,

            "sample_metadata": sample_metadata,
        }

    except Exception as e:

        logger.error(f"Error retrieving collection stats: {e}")

        return {"error": str(e)}


# =============================================================================
# Standalone Test Runner
# =============================================================================

if __name__ == "__main__":

    print("\nInitializing ChromaDB configuration test...\n")

    client, config = initialize_chromadb()

    print(f"  Persistence: {config.persist_directory}")

    print(f"  Embedding model: {config.EMBEDDING_MODEL}")

    print(f"  Document registry: {len(DOCUMENT_REGISTRY)} documents\n")

    print("Document Registry:")

    for doc_id, meta in DOCUMENT_REGISTRY.items():

        print(
            f"  {doc_id:<14}  category={meta['category']:<14}  "
            f"agent={meta['agent_target']:<12}  v{meta['version']}"
        )

    print()

    collection = config.get_or_create_collection(
        client, config.COLLECTION_ALL
    )

    stats = get_collection_stats(collection)

    print("Collection Stats:")

    for key, value in stats.items():

        print(f"  {key}: {value}")

    print("\nChromaDB configuration is fully operational.\n")